service: starwars
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
  credentials: ${file(./.env.yml):credentials}
functions:
  swapi:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
package:
  exclude:
    - .vscode/**
    - .env.yml
    - package.json
    - yarn.lock